package abd.p1.view;

import abd.p1.model.Aficion;
import abd.p1.model.Usuario;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

public class ListaUsuarios extends javax.swing.JPanel {
  
    public ListaUsuarios() {
        initComponents();
        
//        List<Aficion> aficiones = new ArrayList<>();
//        Aficion afi1 = new Aficion();
//        afi1.setTexto("Esgrima");
//        Aficion afi2 = new Aficion();
//        afi2.setTexto("Voleibal");
//        Aficion afi3 = new Aficion();
//        afi3.setTexto("Futbol");
//        Aficion afi4 = new Aficion();
//        afi4.setTexto("Atletismo");    
//        
//        Set<Usuario> amigos = new HashSet<>();
//        Set<Usuario> amigos2 = new HashSet<>();
//        
//        Usuario user4 = new Usuario(foto1);
//        Usuario user5 = new Usuario();
//        user4.setNombre("Iñaki");
//        user5.setNombre("Maritxu");
//        
//        amigos.add(user4);
//        amigos.add(user5);
//        
//        aficiones.add(afi1);
//        aficiones.add(afi2);
//        aficiones.add(afi3);
//        aficiones.add(afi4);
//        
//        Calendar fecha1 = new GregorianCalendar(1985, 4, 14);
//        Date date1 = fecha1.getTime();
//        
//        Calendar fecha2 = new GregorianCalendar(1940, 4, 14);
//        Date date2 = fecha2.getTime();
//        
//        Calendar fecha3 = new GregorianCalendar(1956, 4, 14);
//        Date date3 = fecha3.getTime();
//        
//        ImageIcon foto1 = 
//            new ImageIcon(AvatarPanel.class.getResource("Dino.png"));
//        ImageIcon foto2 = 
//            new ImageIcon(AvatarPanel.class.getResource("Dino2.png"));
//        ImageIcon foto3 = 
//            new ImageIcon(AvatarPanel.class.getResource("Dino3.png"));
//        
//        Usuario user1 = new Usuario("Pepe", date1, "a@a.com", "Pepe", "Varón", "Hombres", "Me gusta los perros",aficiones,foto1,amigos);
//        Usuario user2 = new Usuario("Juan", date2, "e@e.com", "Juan", "Varón", "Mujeres", "Soy vegano", aficiones,foto2,amigos2);
//        Usuario user3 = new Usuario("Maria", date3, "q@q.com", "Maria", "Mujer", "Ambos", "Soy música", aficiones,foto3,amigos2);
//        
//        DefaultListModel<Usuario> modelo = new DefaultListModel<>();
//        modelo.addElement(user1);
//        modelo.addElement(user2);
//        modelo.addElement(user3);
        
        //jlistUsuarios.setModel(modelo);
        //jlistUsuarios.setCellRenderer(new UsuarioCellRenderer());
    }
    
    public void setAmigos(Set<Usuario> amigos){
        DefaultListModel<Usuario> modelo = new DefaultListModel<>();
        
        for(Iterator<Usuario> it = amigos.iterator(); it.hasNext();){
            Usuario usr = it.next();
             modelo.addElement(usr);
        }
       jlistUsuarios.setModel(modelo);
       jlistUsuarios.setCellRenderer(new UsuarioCellRenderer());
    }
    
    public Usuario getSelectedUser(){
        return jlistUsuarios.getSelectedValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlistUsuarios = new javax.swing.JList<>();

        jScrollPane1.setViewportView(jlistUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Usuario> jlistUsuarios;
    // End of variables declaration//GEN-END:variables
}
