package abd.p1.view;

import abd.p1.model.Usuario;

public class MainWindow extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	public MainWindow() {}
	
	public MainWindow(Usuario usuario, boolean nuevoUsuario) {
        initComponents();
        
        addCloseListener();
        
        jTabbedPane1.setTitleAt(0, "Usuarios");
        
        if (nuevoUsuario) {
	        PerfilUsuario perfil = new PerfilUsuario(null,true, usuario);
	        perfil.setEditable(true);
	        perfil.setVisible(true);
        }
        
        /*
        boolean check = false;
        
        InicioSesion ini = new InicioSesion(this,true);
        ini.setVisible(true);
        
        List<Aficion> aficiones = new ArrayList<>();
        Aficion afi1 = new Aficion();
        afi1.setTexto("Esgrima");
        Aficion afi2 = new Aficion();
        afi2.setTexto("Voleibal");
        Aficion afi3 = new Aficion();
        afi3.setTexto("Futbol");
        Aficion afi4 = new Aficion();
        afi4.setTexto("Atletismo");        
        
        aficiones.add(afi1);
        aficiones.add(afi2);
        aficiones.add(afi3);
        aficiones.add(afi4);
        
        ImageIcon foto3 = 
            new ImageIcon(AvatarPanel.class.getResource("Dino3.png"));
       while(ini.isAccept() && !check){ 
            
            if (ini.getCorreo().equals("a@a.com") && ini.getContrasena().equals("1234")) {
                check = true;
                ImageIcon foto1 = 
                    new ImageIcon(AvatarPanel.class.getResource("Dino.png"));
                ImageIcon foto2 = 
                    new ImageIcon(AvatarPanel.class.getResource("Dino2.png"));
                ini.setVisible(false);
                Calendar fecha = new GregorianCalendar(1985, 4, 14);
                Date date = fecha.getTime();
                Set<Usuario> amigos = new HashSet<>();
                Usuario user7 = new Usuario(foto1);
                Usuario user8 = new Usuario(foto2);
                user7.setNombre("Iker");
                user8.setNombre("Maritxu");
                user7.setFechacimiento(date);
                user8.setFechacimiento(date);
                amigos.add(user7);
                amigos.add(user8);
                Usuario user = new Usuario("Antonio", date, "a@a.com", "1234", "Varón", "Hombres", "Me gusta los perros",aficiones,foto3,amigos);
                this.pestanaUsuarios1.setUser(user);
            }
            else{
                JOptionPane.showMessageDialog(this,
                "Usuario Incorrecto",
                "Inicio de sesión",
                JOptionPane.ERROR_MESSAGE);
                ini.setVisible(true);
            }
       
       }
        if (!ini.isAccept()){
            ImageIcon foto1 = 
                    new ImageIcon(AvatarPanel.class.getResource("Dino.png"));
            Usuario user = new Usuario(foto1);
            user.setEmail(ini.getCorreo());
            //FALTA AÑADIR COORDENADAS POR DEFECTO
            user.setContrasena(ini.getContrasena());
            PerfilUsuario perfil = new PerfilUsuario(null,true,user);
            perfil.setEditable(true);
            perfil.setVisible(true);
            this.pestanaUsuarios1.setUser(user);
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pestanaUsuarios1 = new abd.p1.view.PestanaUsuarios();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("tab1", pestanaUsuarios1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private abd.p1.view.PestanaUsuarios pestanaUsuarios1;
    // End of variables declaration//GEN-END:variables

	
	private boolean _isClosed = false;
    
    public boolean isClosed() {
		return _isClosed;
	}
    
    public synchronized void close() {
    	setVisible(false);
    	_isClosed = true;
    	notify();
    }
    
    public synchronized void waitUntilClose() {
    	while (!isClosed()) {
    		try {
    			wait();
    		} catch (InterruptedException e) {
    			
    		}
    	}
    }
    
    private void addCloseListener() {
        addWindowListener(new java.awt.event.WindowAdapter() {
        	@Override
        	public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        		close();
        	}
        });
    }
}
