package abd.p1.view;

import abd.p1.controller.Facade;
import abd.p1.model.Usuario;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class PestanaUsuarios extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	private Usuario user;
    /**
     * Creates new form PestanaUsuarios
     */
    public PestanaUsuarios(Usuario usuario) {
        user = usuario;
        initComponents();
        showFilteredUsers();
        
        // Para que se modifique la lista cuando se cambie el textBox:
        nombreFiltro.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
            	showFilteredUsers();
            }
            public void removeUpdate(DocumentEvent e) {
            	showFilteredUsers();
            }
            public void insertUpdate(DocumentEvent e) {
            	showFilteredUsers();
            }
          });
    }
    
     /**
     * @return the user
     */
    public Usuario getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(Usuario user) {
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaUsuarios1 = new abd.p1.view.ListaUsuarios();
        filtrar = new javax.swing.JCheckBox();
        filtroAmigos = new javax.swing.JCheckBox();
        nombreFiltro = new javax.swing.JTextField();
        buttonModificarPerfil = new javax.swing.JButton();
        buttonVerPerfil = new javax.swing.JButton();

        filtrar.setText("Filtrar por nombre:");
        filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionPerformed(evt);
            }
        });

        filtroAmigos.setText("Mostrar sólo amigos");
        filtroAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroAmigosActionPerformed(evt);
            }
        });

        nombreFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFiltroActionPerformed(evt);
            }
        });

        buttonModificarPerfil.setText("Modificar mi perfil");
        buttonModificarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarPerfilActionPerformed(evt);
            }
        });

        buttonVerPerfil.setText("Ver perfil seleccionado");
        buttonVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaUsuarios1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filtroAmigos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filtrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreFiltro)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(buttonModificarPerfil)
                .addGap(67, 67, 67)
                .addComponent(buttonVerPerfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtrar)
                    .addComponent(nombreFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(filtroAmigos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonModificarPerfil)
                    .addComponent(buttonVerPerfil))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonModificarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarPerfilActionPerformed
       //user = this.getUser();
       PerfilUsuario perfil = new PerfilUsuario(null, true, user, null);
       UserPanel panel = new UserPanel();
       panel = perfil.getUserPanel1();
       panel.setUser(user);
       perfil.setVisible(true);
       perfil.setEditable(true);
    }//GEN-LAST:event_buttonModificarPerfilActionPerformed

    private void buttonVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerPerfilActionPerformed
        Usuario usr = listaUsuarios1.getSelectedUser();
        if(usr != null){
            PerfilUsuario perfil = new PerfilUsuario(null, true, usr, this.user);
            perfil.setTitle("Información de perfil");
            perfil.setEditable(false);
            perfil.setVisible(true);
       }
    }//GEN-LAST:event_buttonVerPerfilActionPerformed

    private void filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionPerformed
        showFilteredUsers();
    }//GEN-LAST:event_filtrarActionPerformed

    private void filtroAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroAmigosActionPerformed
        if (!user.getAmigos().isEmpty()){
            if (filtroAmigos.isSelected()) {
                Set<Usuario> amigos = new HashSet<>();
                amigos = this.user.getAmigos();
                listaUsuarios1.setUsuariosRelacionados(amigos);
            }
        }
    }//GEN-LAST:event_filtroAmigosActionPerformed

    private void nombreFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFiltroActionPerformed
    	showFilteredUsers();
    }//GEN-LAST:event_nombreFiltroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonModificarPerfil;
    private javax.swing.JButton buttonVerPerfil;
    private javax.swing.JCheckBox filtrar;
    private javax.swing.JCheckBox filtroAmigos;
    private abd.p1.view.ListaUsuarios listaUsuarios1;
    private javax.swing.JTextField nombreFiltro;
    // End of variables declaration//GEN-END:variables

    void showFilteredUsers() {
    	String filterTxt = null;
        if (filtrar.isSelected()) {
        	filterTxt = nombreFiltro.getText();
        }
    	List<Usuario> usrs = Facade.getInstance().getUsuarioController().listUsers(user, filterTxt, false);
        listaUsuarios1.setUsuariosRelacionados(usrs);
    }
}
